version: "3"
   
services:

  postgres:
    image: postgres:9.6-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    env_file:
      - ./.envs/.postgres
    ports:
      - 5432:5432

  web:
    build:
      context: .
      dockerfile: ./dockers/web/Dockerfile
    command: sh /run_web.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.web
      - ./.envs/.postgres
    depends_on:
      - postgres
